config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  get '/pages/selects', to: 'pages#selects', as: :pages_selects
  get '/pages/h_forms', to: 'pages#h_forms', as: :pages_h_forms

  resources :addresses

  get '/regions/countries', to: 'regions#counries', as: :countries
  get '/regions/states', to: 'regions#states', as: :states
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :state

  validates :title, :street, :street_number, :zipcode, presence: true

  def country
    self.try(:state).try(:country)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states, dependent: :destroy

  validates :name, presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  
  validates :name, presence: true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = Address.all
  end

  def show; end

  def new
    @address = Address.new
  end

  def edit; end

  def create
    @address = Address.new(resource_params)
    if @address.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to addresses_path, notice: "Dirección agregada correctamente" }
      end
    else
      flash[:alert] = "Ocurrió un error al agregar la dirección"
      render :new
    end
  end

  def update
    if @address.update(resource_params)
      flash[:notice] = "Dirección actualizada correctamente"
      redirect_to addresses_path
    else
      flash[:alert] = "Ocurrió un error al modificar los datos de la dirección"
      render :edit
    end

  end

  def destroy
    if @address.destroy
      flash[:notice] = "Dirección eliminada!"
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to addresses_path, notice: "Dirección agregada correctamente" }
      end
    else
      flash[:error] =  "No se puede eliminar la dirreción"
      redirect_to addresses_path
    end
  end

  private
    def set_resource
      @address = Address.find(params[:id])
    end

    def resource_params
      accessible = []
      accessible << %i[title street street_number zipcode appt_floor appt_number]
      accessible << %i[state country state_id country_id]
      params.require(:address).permit(accessible)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
  end

  def selects
  end

  def h_forms
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def countries
    @countries = Country.all

    render json: @countries.pluck(:id, :name)
  end

  def states
    # ID => country_id
    #
    if params[:id].present?
      @states = State.where(country_id: params[:id])
    else
      @states = State.all
    end

    render json: @states.pluck(:id, :name)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/addresses/_address.html.erb
<div class="card text-start mb-3">
  <div class="card-body">
    <%= tag.h5 address.title, class: "cart-title" %>
    <%= tag.h6 "#{[address.street, address.street_number].join(", ")}, CP: #{address.zipcode}", class: "cart-subtitle mb-2 text-muted" %>
    <%= tag.p [address.try(:state).try(:name), address.try(:country).try(:name)].join(", "), class: "card-text" %>

    <div class="text-end">
      <%= link_to "Modificar", edit_address_path(address), class: "card-link" %>
      <%= link_to "Eliminar", address_path(address), method: :delete, data: { confirm: "Estas seguro que quieres eliminar esta dirección?" },  class: "card-link" %>
    </div>
  </div>
</div>

app/views/addresses/_form.html.erb
<%= turbo_frame_tag "new_address" do %>
  <%= form_with model: address,
                html: {
                  class: "mb-5 text-start",
                  data: {
                    controller: "form",
                    action: "turbo:submit-end->form#reset"
                  }
                } do |f| %>
    <% if address.errors.any? %>
      <div class="row">
        <div class="col-12">
          <div class="alert alert-danger alert-dismissible fade show shadow" role="alert">
            <div class="row no-glutters">
              <div class="col-12 text-start">
                <ul>
                  <% address.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="mb-3">
      <%= f.label :title, "Título de dirección:", class: "form-label" %>
      <%= f.text_field :title, class: "form-control" %>
      <%= tag.div "Descripción de la dirección", class: "form-text" %>
    </div>

    <div class="row mb-3">
      <div class="col-8">
        <%= f.label :street, "Calle (Avenida) (sin número):", class: "form-label" %>
        <%= f.text_field :street, class: "form-control" %>
      </div>

      <div class="col-4">
        <%= f.label :street_number, "Número:", class: "form-label" %>
        <%= f.text_field :street_number, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col-6">
        <%= f.label :appt_floor, "Piso:", class: "form-label" %>
        <%= f.text_field :appt_floor, class: "form-control" %>
      </div>

      <div class="col-6">
        <%= f.label :appt_number, "Dto/Oficina:", class: "form-label" %>
        <%= f.text_field :appt_number, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-5">
        <div class="form-floating mt-2">
          <%= select_tag "country",
                        options_for_select(Country.order(:name).pluck(:name, :id)),
                        include_blank: true,
                        data: {
                          controller: "regions",
                          action: "change->regions#handleSelectChange",
                          targetbox: "address_state_id"
                        },
                        class: "form-control" %>
          <%= label_tag "country", "País:" %>
        </div>
      </div>

      <div class="col-5">
        <div class="form-floating mt-2">
          <%= f.select :state_id,
                        options_for_select(State.order(:name).pluck(:name, :id)),
                        { include_blank: true },
                        {
                          data: {},
                          disabled: true,
                          class: "form-control"
                        } %>
          <%= f.label :state_id, "Provincia:" %>
        </div>
      </div>

      <div class="col-2">
        <%= f.label :zipcode, "Código postal:", class: "form-label" %>
        <%= f.text_field :zipcode, class: "form-control" %>
      </div>
    </div>

    <div class="row justify-content-center mt-5">
      <div class="col-4 mx-auto text-center">
        <%= link_to "Volver", addresses_path, class: "btn btn-outline-dark" %>
        <%= f.submit "Confirmar", data: { "form-target": "button" }, class: "btn btn-dark" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/addresses/create.turbo_stream.erb
<%= turbo_stream.append "addresses", partial: "address", locals: { address: @address } %>

app/views/addresses/edit.html.erb
<h1 class="display-7 fw-bold mb-4">Hotwire en la practica</h1>

<div class="row justify-content-evenly mt-5">
  <div class="col-6 text-start">
    <%= tag.h4 "Modificar dirección #{@address.title}", class: "text-center mb-5" %>

    <%= render partial: "addresses/form", locals: { address: @address } %>
  </div>
</div>

app/views/addresses/index.html.erb
<h1 class="display-7 fw-bold mb-4">Hotwire en la practica</h1>

<div class="row justify-content-evenly mt-5">
  <div class="col-8 mx-auto">
    <div class="mb-5">
      <%= turbo_frame_tag "new_address" do %>
        <%= link_to "Agregar dirección", new_address_path, class: "btn btn-sm btn-dark" %>
      <% end %>
    </div>

    <%= tag.h4 "Mis direcciones", class: "text-start mb-3" unless @addresses.nil? %>

    <%= turbo_frame_tag "addresses" do %>
      <%= render partial: "addresses/address", collection: @addresses %>
    <% end %>
  </div>
</div>

app/views/addresses/new.html.erb
<h1 class="display-7 fw-bold mb-4">Hotwire en la practica</h1>

<div class="row justify-content-evenly mt-5">
  <div class="col-8 mx-auto text-start">
    <%= tag.h4 "Agregar una dirección nueva", class: "text-center mb-5" %>

    <%= render partial: "addresses/form", locals: { address: @address } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <title>Stimulus Demo</title>
    <%= stimulus_include_tags %>
    <%= javascript_include_tag "turbo", type: "module-shim" %>
    <%= yield :head %>
  </head>

  <body>
    <div class="container">
      <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <li><%= link_to "Home", root_path, class: "nav-link px-2 link-secondary" %></li>
          <li><%= link_to "Selects con Stimulus", pages_selects_path, class: "nav-link px-2 link-dark" %></li>
          <li><%= link_to "Formularios con Hotwire", addresses_path, class: "nav-link px-2 link-dark" %></li>
        </ul>

        <div class="col-md-3 text-end">
        </div>
      </header>

      <div class="px-4 py-5 my-5 text-center">
        <%= yield %>
      </div>
    </div>

    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <%#= javascript_include_tag "application" %>
    <%= yield :scripts %>      
  </body>
</html>

app/views/pages/h_forms.html.erb
<h1 class="display-7 fw-bold mb-4">Hotwire en la practica</h1>

<div class="row justify-content-evenly mt-5">
  <div class="col-5">
    <%= tag.h4 "Listado de direcciones agregadas", class: "text-start mb-5" %>

    <%= render partial: "addresses/address" %>
  </div>

  <div class="col-6 text-start">
    <%= tag.h4 "Formulario de direcciones", class: "text-center mb-5" %>

    <%= render partial: "addresses/form", locals: { address: @address } %>
  </div>
</div>

app/views/pages/index.html.erb
<%= image_tag "stimulusjs.png", alt: "Stimulus JS", width: 72, class: "d-block mx-auto mb-4" %>
<h1 class="display-5 fw-bold">Stimulus & Hotwire</h1>
<div class="col-lg-6 mx-auto">
  <p class="lead mb-4">Mejoras practicas y usecases de aplicación de Stimulus.js y Hotwire en una aplicación Rails. Los 40 kbytes de Javascript que reemplazan un framework completo.</p>
  <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mt-5">
    <%= link_to "Selects con Stimulus", pages_selects_path, class: "btn btn-outline-dark btn-block px-4 me-sm-3" %>
    <%= link_to "Formularios con Hotwire", addresses_path, class: "btn btn-outline-dark tn-block  px-4 me-sm-3" %>
  </div>
</div>

app/views/pages/selects.html.erb
<h1 class="display-7 fw-bold mb-4">Actualización dinámica de datos con Stimulus</h1>

<div class="row justify-content-md-center mt-5">
  <div class="col-4">
    <div class="form-group">
      <div class="form-floating">
        <%= select_tag "country",
                        options_for_select(Country.order(:name).pluck(:name, :id)),
                        include_blank: true,
                        data: {
                          controller: "regions",
                          action: "change->regions#handleSelectChange",
                          targetbox: "state"
                        },
                        class: "form-select" %>
        <%= label_tag "country", "Selecciona un país" %>
      </div>
    </div>
  </div>

  <div class="col-4">
    <div class="form-group">
      <div class="form-floating">
        <%= select_tag "state",
                        options_for_select(State.order(:name).pluck(:name, :id)),
                        include_blank: true,
                        disabled: true,
                        data: {},
                        class: "form-select" %>
        <%= label_tag "state", "Selecciona un provincia" %>
      </div>
    </div>
  </div>
</div>